//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/GameInputs/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""b4c86fb8-0363-450f-a2ee-8e54a2020a70"",
            ""actions"": [
                {
                    ""name"": ""MouseMoveAndInteract"",
                    ""type"": ""Button"",
                    ""id"": ""ef42e1e1-64ea-4638-8e60-d18d3bb16dd3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractionButton"",
                    ""type"": ""Button"",
                    ""id"": ""aafde643-6ad6-45d0-bf79-52567d7485bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TextSkip"",
                    ""type"": ""Button"",
                    ""id"": ""6fa15e37-41f9-4b47-a42f-982e6057f827"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""eb222c42-99f8-4888-a8a2-b87ce97b50a6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveAndInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ced0de56-fd1a-4beb-8f57-0f5477659565"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractionButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""674f541c-3703-41d5-9199-6286a4eda031"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TextSkip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_MouseMoveAndInteract = m_Player.FindAction("MouseMoveAndInteract", throwIfNotFound: true);
        m_Player_InteractionButton = m_Player.FindAction("InteractionButton", throwIfNotFound: true);
        m_Player_TextSkip = m_Player.FindAction("TextSkip", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_MouseMoveAndInteract;
    private readonly InputAction m_Player_InteractionButton;
    private readonly InputAction m_Player_TextSkip;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseMoveAndInteract => m_Wrapper.m_Player_MouseMoveAndInteract;
        public InputAction @InteractionButton => m_Wrapper.m_Player_InteractionButton;
        public InputAction @TextSkip => m_Wrapper.m_Player_TextSkip;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @MouseMoveAndInteract.started += instance.OnMouseMoveAndInteract;
            @MouseMoveAndInteract.performed += instance.OnMouseMoveAndInteract;
            @MouseMoveAndInteract.canceled += instance.OnMouseMoveAndInteract;
            @InteractionButton.started += instance.OnInteractionButton;
            @InteractionButton.performed += instance.OnInteractionButton;
            @InteractionButton.canceled += instance.OnInteractionButton;
            @TextSkip.started += instance.OnTextSkip;
            @TextSkip.performed += instance.OnTextSkip;
            @TextSkip.canceled += instance.OnTextSkip;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @MouseMoveAndInteract.started -= instance.OnMouseMoveAndInteract;
            @MouseMoveAndInteract.performed -= instance.OnMouseMoveAndInteract;
            @MouseMoveAndInteract.canceled -= instance.OnMouseMoveAndInteract;
            @InteractionButton.started -= instance.OnInteractionButton;
            @InteractionButton.performed -= instance.OnInteractionButton;
            @InteractionButton.canceled -= instance.OnInteractionButton;
            @TextSkip.started -= instance.OnTextSkip;
            @TextSkip.performed -= instance.OnTextSkip;
            @TextSkip.canceled -= instance.OnTextSkip;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMouseMoveAndInteract(InputAction.CallbackContext context);
        void OnInteractionButton(InputAction.CallbackContext context);
        void OnTextSkip(InputAction.CallbackContext context);
    }
}
